# -*- coding: utf-8 -*-
"""Información delictiva del municipio de Bucaramanga.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vkIg8gQApbeSfnqcKYlTaojWCpG0ocDl

#Proyecto Bootcamp Analisis de Datos
## Informacion delictiva del municipio de Bucaramga - Detectar Variables y patrones para predecir y reducir la criminalidad

##Presentado por Andres Camilo Lopez - Analista de Datos
##CC. 1.053.807.414

###PROBLEMATICA

####La creciente incidencia de delitos en diferentes barrios de Bucaramanga ha generado preocupación entre los residentes y las autoridades locales. La falta de un análisis inicial de las variables asociadas a la delincuencia (como los tipos de armas, horarios, ubicaciones y características de las víctimas) dificulta la implementación de políticas preventivas efectivas. Se necesita identificar patrones específicos que puedan ayudar a las autoridades a predecir y reducir la criminalidad en áreas de alta incidencia.

###OBJETIVO

*   Analizar los patrones de conducta delictiva en Bucaramanga.
*   Examinar las relaciones entre tipo de delito, horario, ubicación (barrio), edad y género de las personas afectadas, así como el tipo de arma utilizada.
*   Proporcionar recomendaciones a las autoridades para la implementación de medidas de seguridad en los barrios más afectados y sugerir horarios de patrullaje.

###FUENTE DE DATOS

Información de los delitos ocurridos en el municipio según la modalidad y conducta delictiva, barrios y comunas de ocurrencia, armas y medios empleados, móvil del agresor y de la víctima, curso de vida y género de la víctima, con una desagregación temporal por mes, día, y hora de ocurrencia. de enero 2016 a octubre 2023

Se va a realizar el analisis de los datos de los años 2022 y 2023.

Se cuentan con 28116 registros donde cada fila es un una fila, un delito o crimen.

Los datos se tomaron de https://www.datos.gov.co/Seguridad-y-Defensa/Informaci-n-delictiva-del-municipio-de-Bucaramanga/x46e-abhz/about_data
datos abierto del gobierno nacional

###CRONOGRAMA
"""

#@title 1. Importar librerias

import pandas as pd
import plotly.express as px

#@title 2. Cargar Datos

datos = pd.read_excel('/content/drive/MyDrive/Información delictiva del municipio de Bucaramanga/informacion_delictiva_municipio_bucaramanga.xlsx',usecols=[0,1,2,3,4,5,6,8,9,14,16,20,24])

#@title 3. Visualizar Metadatos

#datos.head()
datos.info()

##@title Convertir Datos

#convertir el nombre del dia en mayuscula
datos['DIA_NOMBRE'] = datos['DIA_NOMBRE'].str.upper()
#print(datos['DIA_NOMBRE'])

#@title 4. Limpiar Datos
#consultar valores nulos
#print(datos[datos['EDAD'].isna()])
#se halla la media de edad y se reemplaza nulos y no disponible por 0
datos.loc[datos['EDAD'] == 'NO DISPONIBLE', 'EDAD'] = 0
datos.loc[datos['EDAD'] == 'NaN', 'EDAD'] = 0
datos['EDAD'] = datos['EDAD'].astype(float)
media = datos['EDAD'].mean()
#se reemplazan los valores nulos por la media - rellene los valores faltantes de edad y que realice el cambio en el dataframe
datos.fillna({'EDAD': media}, inplace=True)
print(datos[datos['EDAD'].isna()])
datos.describe()
#ahi un dato en la columna edad que es atipico max edad 125
#********************************************************************
#Valores duplicados
filas_duplicadas = datos[datos.duplicated()]
filas_duplicadas.to_excel('filas_duplicadas.xlsx', index=False)
print(filas_duplicadas)
datos.drop_duplicates(inplace=True)
filas_duplicadas = datos[datos.duplicated()]
datos.duplicated().sum()
print(filas_duplicadas)

#@title 5. Filtrar datos
#filtrar po año, mes, dia , hora
datos['Año'] = datos['FECHA_HECHO'].dt.year
datos['Mes'] = datos['FECHA_HECHO'].dt.month_name()
datos['Dia'] = datos['FECHA_HECHO'].dt.dayofweek
#funcion para pasar dia a español dependiendo el numero del dia que arroje dayofweek
def dia_de_la_semana_en_espanol(dia_ingles):
  dias_espanol = {0: 'Lunes', 1: 'Martes', 2: 'Miércoles', 3: 'Jueves', 4: 'Viernes', 5: 'Sábado', 6: 'Domingo'}
  return dias_espanol[dia_ingles]
datos['Dia_español'] = datos['FECHA_HECHO'].dt.dayofweek.apply(lambda x: dia_de_la_semana_en_espanol(x))
datos['Hora'] = datos['FECHA_HECHO'].dt.hour
#conteo de registros del 2022 y 2023
conteo_2023 = datos[datos['Año'] == 2023].shape[0]
conteo_2022 = datos[datos['Año'] == 2022].shape[0]
datos

#@title 6. Procesar Datos
datos_2022 = datos[datos['Año'] == 2022]
datos_2023 = datos[datos['Año'] == 2023]
#datos2022

# Agrupar por descripción y contar 2022 y 2023
conteo_por_descripcion_2022 = datos_2022.groupby('DESCRIPCION_CONDUCTA').size()
conteo_por_descripcion_2023 = datos_2023.groupby('DESCRIPCION_CONDUCTA').size()
#conteo_por_descripcion_2023

# conteo de las armas o medios utilizados para los delitos 2022 y 2023 excluye no disponible y no reportado
excluir = ['NO DISPONIBLE', 'NO REPORTADO']
datos_filtrados = datos[~datos['ARMAS_MEDIOS'].isin(excluir)]
conteo_por_arma = datos_filtrados.groupby('ARMAS_MEDIOS').size()
#conteo_por_arma

#Sexo de la victima del delito según la Policía
genero = datos.groupby('SEXO').size()
#genero

#Distribución de la edad de las víctimas se identifico un dato erroneo se excluyo edad de 125 años
df_2022 = datos[(datos['Año'] == 2022) & (datos['EDAD'] < 100)].groupby(['EDAD']).size().reset_index(name='Frecuencia')
df_2023 = datos[(datos['Año'] == 2023) & (datos['EDAD'] < 100)].groupby(['EDAD']).size().reset_index(name='Frecuencia')
#se combinan los años para mostrar en dispersion
df_combined = pd.concat([df_2022, df_2023])

#tendencia por mes de los delitos en cada año
tendencia_2022 = datos[datos['Año'] == 2022].groupby('Mes').size()
tendencia_2023 = datos[datos['Año'] == 2023].groupby('Mes').size()
#tendencia_2022
#tendencia_2023

#@title 7. Generar Graficas

# Crear el gráfico de barras conteo por descripcion de conducta para 2022
fig_2022 = px.bar(conteo_por_descripcion_2022,
            x=conteo_por_descripcion_2022.values,
            y=conteo_por_descripcion_2022.index,
            labels={'x': 'Frecuencia', 'y': 'Descripción de Conducta'},title='Frecuencia de Descripciones de Conducta',
            text_auto=True,
            color = conteo_por_descripcion_2022)

# Crear el gráfico de barras conteo por descripcion de conducta para 2023
fig_2023 = px.bar(conteo_por_descripcion_2023,
            x=conteo_por_descripcion_2023.values,
            y=conteo_por_descripcion_2023.index,
            labels={'x': 'Frecuencia', 'y': 'Descripción de Conducta'},title='Frecuencia de Descripciones de Conducta',
            text_auto=True,
            template='plotly_dark',
            color = conteo_por_descripcion_2023)

# grafico de barras verticales armas o medios utilizados
fig_armas = px.bar(conteo_por_arma,
            x=conteo_por_arma.index,
            y=conteo_por_arma.values,
            labels={'x': 'Arma', 'y': 'Frecuencia'},
            title='Armas utilizadas para los delitos',
            text_auto=True,
            color = conteo_por_arma)

# Mostrar los gráficos
fig_2022.show()
fig_2023.show()
fig_armas.show()

# grafico tipo pie genero de la victima de los delitos
fig_genero = px.pie(genero,
            values=genero.values,
            names=genero.index,
            labels={'x': 'Genero', 'y': 'Frecuencia'},
            title='Genero victima de los delitos',)
#dividir torta
fig_genero.update_traces(marker = dict(line = dict(color = 'white', width = 4)))

#Distribución de la edad de las víctimas
fig_edad = px.scatter(df_combined, x='EDAD', y='Frecuencia', color='EDAD')

#tendencia por mes 2022 - 2023
fig_tendencia_2022 = px.line(tendencia_2022,
            x=tendencia_2022.index,
            y=tendencia_2022.values,
            labels={'x': 'Mes', 'y': 'Frecuencia'},
            title= 'Delitos por Mes')

fig_tendencia_2022.update_traces(line = dict(dash = "dot", width = 4, color = "red"),
                  marker = dict(color = "darkblue", size = 20, opacity = 0.8))

fig_tendencia_2023 = px.line(tendencia_2023,
            x=tendencia_2023.index,
            y=tendencia_2023.values,
            labels={'x': 'Mes', 'y': 'Frecuencia'},
            title= 'Delitos por Mes')

fig_tendencia_2023.update_traces(line = dict(dash = "dot", width = 4, color = "blue"),
                  marker = dict(color = "darkblue", size = 20, opacity = 0.8))


# Mostrar los gráficos

fig_genero.show()
fig_edad.show()
fig_tendencia_2022.show()
fig_tendencia_2023.show()

"""###CONCLUSIONES

1. Delito más recurrente: El hurto a personas es, según los datos presentados, el delito más comúnmente denunciado en el periodo analizado. Esto sugiere que este tipo de delito representa una problemática social relevante y requiere de mayor atención por parte de las autoridades.

  Desbalance en la distribución de delitos: La gran diferencia entre la frecuencia del hurto a personas y otros delitos indica que existe un desbalance en la distribución de los tipos de delitos denunciados. Es posible que otros delitos estén subdenunciados o que existan factores sociales o económicos que favorezcan la ocurrencia de este tipo de hurtos.

  Necesidad de políticas específicas: La alta frecuencia del hurto a personas sugiere la necesidad de implementar políticas públicas y estrategias de prevención específicas para combatir este tipo de delito. Esto podría incluir mayor vigilancia en zonas de alta incidencia, campañas de prevención y programas de rehabilitación para los delincuentes.

  Impacto social: La elevada tasa de denuncias por hurto a personas puede tener un impacto significativo en la percepción de seguridad de la población, afectando la calidad de vida y el desarrollo económico de las comunidades.

  Limitaciones de los datos: Es importante considerar que este gráfico presenta una visión parcial de la realidad, ya que solo muestra los datos de las denuncias formalizadas. Puede existir un número desconocido de casos no denunciados.
  
  .Predominancia de Armas Blancas: El uso de armas blancas como principal instrumento en la comisión de delitos sugiere que este tipo de delitos, como robos y asaltos, son más comunes y que los delincuentes optan por herramientas fácilmente accesibles y menos rastreables.

2. Baja Frecuencia de Armas de Fuego: La baja frecuencia de uso de armas de fuego indica que este tipo de delitos, aunque más graves, son menos comunes. Esto podría deberse a restricciones legales, dificultades para obtener armas de fuego o a una menor disponibilidad en el mercado negro.

  Diversidad de Armas: A pesar de la predominancia de las armas blancas, el gráfico muestra una variedad de armas utilizadas, lo que sugiere que los delincuentes adaptan sus métodos según el tipo de delito y las circunstancias.

  Posibles Factores Influyentes: La disponibilidad de armas, las características de los delitos y las políticas de control de armas pueden influir en la elección de las armas utilizadas.

3. Para el genero no se encontro una variante o discriminacion ya que los porcentajes fueron muy similares en los datos que se trataron.

4. Población Joven: La distribución sugiere que la población en estudio tiene una mayor proporción de individuos jóvenes en comparación con los de edad avanzada. Esto podría indicar una población con una alta tasa de natalidad o una migración significativa de jóvenes hacia la zona en estudio.

  Disminución de la Frecuencia con la Edad: La tendencia a la baja en la frecuencia a medida que aumenta la edad podría ser explicada por diversos factores, como una mayor tasa de mortalidad en edades avanzadas, una menor tasa de natalidad en el pasado o una migración de personas mayores hacia otras regiones.

  Posibles Grupos de Edad: La gráfica podría revelar la existencia de grupos de edad específicos con mayor o menor frecuencia. Por ejemplo, se podría observar un pico en la frecuencia en edades correspondientes a la juventud (18-25 años) o en edades de jubilación.

  Sesgos en los Datos: Es importante considerar que la distribución observada podría estar influenciada por sesgos en la recopilación de los datos. Por ejemplo, si los datos provienen de una encuesta en línea, es posible que haya una subrepresentación de personas mayores que no utilizan internet.

5. Tendencias similares: Ambas gráficas muestran patrones similares de aumento y disminución en la frecuencia de delitos a lo largo del año. Esto sugiere que existen factores estacionales comunes que afectan a ambos tipos de delitos.

  Meses con mayor incidencia: Se observa un aumento en la frecuencia de delitos durante ciertos meses del año y una disminución en otros. Esto podría estar relacionado con factores como las vacaciones, las condiciones climáticas, eventos especiales o cambios en las rutinas diarias de las personas.

  Condiciones climáticas: Las condiciones climáticas, como el aumento de las horas de luz durante el verano o las condiciones climáticas adversas durante el invierno, pueden influir en la ocurrencia de ciertos tipos de delitos.

  Eventos especiales: Eventos como fiestas, feriados o eventos deportivos pueden atraer a grandes multitudes y aumentar la oportunidad para la comisión de delitos.

  Cambios en las rutinas diarias: Los cambios en las rutinas diarias de las personas, como el inicio y finalización del horario escolar o laboral, pueden influir en la oportunidad para la comisión de delitos.
"""